### ISSUE TITLE
Enhancements for station overview

### ISSUE THREAD

**Issue by SvetaMemphis** [memphisdev/memphis-ui#202]
1. Keep the disconnected producers in the Producer section while the message is still in the station with an indication active/not active.
2. Also keep the disconnected consumers in the Consumer section.
3. Adding metadata in the message section such as who is the user who produced the msg.

![image](https://user-images.githubusercontent.com/74717402/173787317-c9220436-98ce-4869-877e-9dd0a43452ee.png)

**Comment by avrhamNeeman** [comment]
Done
