### ISSUE TITLE
sandbox openening modal should be rewrite

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-ui#275]
<img width="607" alt="Screen Shot 2022-07-19 at 18 08 21" src="https://user-images.githubusercontent.com/70286779/179784586-51db4664-aaaa-4e87-939f-a02683070598.png">

Please bear in mind that it is a sandbox environment under constant modifications. ->
Please remember that this is a sandbox environment and is under constant modifications.

Downtime and bugs might occur. ->
Downtimes might occur.

+

Add more space between the social icons

**Comment by NabajitS** [comment]
Can I get working on this issue?

**Comment by Avitaltrifsik** [comment]
@NabajitS Sure, please open a PR to staging when you're ready 🙂

**Comment by yanivbh1** [comment]
@NabajitS How is it going :)?

**Comment by NabajitS** [comment]
I'm working on it. Was stuck as I had never worked with docker before, I'll get it done quickly

**Comment by idanasulinmemphis** [comment]
Thanks @NabajitS this has been merged and will be released on the next version
