### ISSUE TITLE
Show amount of replica sets based on the actual availability

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-ui#277]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

![Screen Shot 2022-07-28 at 15 22 56](https://user-images.githubusercontent.com/70286779/181503926-13cf9858-0bc4-4411-80fe-c3a45c8aadcf.png)

**Comment by idanasulinmemphis** [comment]
Thanks @SvetaMemphis for the this bugfix, will be released on the coming version
