### ISSUE TITLE
Split code example to smaller functions

### ISSUE THREAD

**Issue by yanivbh1** [memphisdev/memphis-ui#279]
Hey,
We need to add a selection box for users to have either complete code example or split into small functions

![Screen Shot 2022-07-24 at 10 43 02](https://user-images.githubusercontent.com/70286779/180637432-93eaf603-fbf5-42df-9755-20a4779fdc17.png)

**Comment by yanivbh1** [comment]
@idanasulinmemphis are we closing this one?

**Comment by idanasulinmemphis** [comment]
We decided to currently leave the code examples as a main function creates a Consumer / Producer.
So closing this issue without commits
