### ISSUE TITLE
User name not displayed

### ISSUE THREAD

**Issue by avrhamNeeman** [memphisdev/memphis-ui#282]
Sandbox platform - After creating the station, my user name doesn't appear in the created by section of factory and station.
![Screen Shot 2022-08-03 at 17 19 29](https://user-images.githubusercontent.com/74565114/182631885-f167a75b-1b28-4c01-be65-9f5970777f17.png)

**Comment by shay23b** [comment]
Hey, can you try recreate the bug?

**Comment by yanivbh1** [comment]
@avrhamNeeman @shay23b please update a status and place a label of in-progress

**Comment by idanasulinmemphis** [comment]
Fixed and will be released on the coming version
